list(APPEND SLIC3R_GUI_SOURCES
    GUI/ProjectState.hpp
    GUI/JusPrin/Agent/AgentHost.cpp
    GUI/JusPrin/Agent/AgentHost.hpp
    GUI/JusPrin/Agent/AgentProtocol.hpp
    GUI/JusPrin/Agent/AgentWebView.cpp
    GUI/JusPrin/Agent/AgentWebView.hpp
    GUI/JusPrin/Agent/DeterministicMockAgent.cpp
    GUI/JusPrin/Agent/DeterministicMockAgent.hpp
    GUI/JusPrin/CanvasPresentationController.cpp
    GUI/JusPrin/CanvasPresentationController.hpp
    GUI/JusPrin/Shell/AgentPane.cpp
    GUI/JusPrin/Shell/AgentPane.hpp
    GUI/JusPrin/Shell/ShellController.cpp
    GUI/JusPrin/Shell/ShellController.hpp
    GUI/JusPrin/Shell/ShellTheme.cpp
    GUI/JusPrin/Shell/ShellTheme.hpp
    GUI/JusPrin/Shell/StatusRow.cpp
    GUI/JusPrin/Shell/StatusRow.hpp
    GUI/JusPrin/Workspace/FakeWorkspace.hpp
    GUI/JusPrin/Workspace/OrcaWorkspaceAdapter.cpp
    GUI/JusPrin/Workspace/OrcaWorkspaceAdapter.hpp
    GUI/JusPrin/Workspace/Workspace.hpp
)
