list(APPEND SLIC3R_GUI_SOURCES
    GUI/ProjectState.hpp
    GUI/JusPrin/Agent/IntentChecks.hpp
    GUI/JusPrin/Agent/AgentHost.cpp
    GUI/JusPrin/Agent/AgentHost.hpp
    GUI/JusPrin/Agent/AgentConfiguration.cpp
    GUI/JusPrin/Agent/AgentConfiguration.hpp
    GUI/JusPrin/Agent/AgentProtocol.hpp
    GUI/JusPrin/Agent/AgentService.hpp
    GUI/JusPrin/Agent/AgentSetup.cpp
    GUI/JusPrin/Agent/AgentSetup.hpp
    GUI/JusPrin/Agent/AgentWebView.cpp
    GUI/JusPrin/Agent/AgentWebView.hpp
    GUI/JusPrin/Agent/ManufacturingHistory.cpp
    GUI/JusPrin/Agent/ManufacturingHistory.hpp
    GUI/JusPrin/Agent/OpenAIHttpTransport.cpp
    GUI/JusPrin/Agent/OpenAIResponsesAgent.cpp
    GUI/JusPrin/Agent/OpenAIResponsesAgent.hpp
    GUI/JusPrin/Agent/ProductState.hpp
    GUI/JusPrin/Agent/ProjectPersistence.cpp
    GUI/JusPrin/Agent/ProjectPersistence.hpp
    GUI/JusPrin/Agent/ProjectStateDocument.cpp
    GUI/JusPrin/Agent/ProjectStateDocument.hpp
    GUI/JusPrin/Agent/ToolExecution.hpp
    GUI/JusPrin/Agent/ToolExecutionCoordinator.cpp
    GUI/JusPrin/Agent/ToolExecutionCoordinator.hpp
    GUI/JusPrin/Agent/ToolRegistry.cpp
    GUI/JusPrin/Agent/ToolRegistry.hpp
    GUI/JusPrin/Agent/ToolResults.cpp
    GUI/JusPrin/Agent/ToolResults.hpp
    GUI/JusPrin/PrinterSetup/PrinterSetupTypes.hpp
    GUI/JusPrin/PrinterSetup/PrinterCatalog.cpp
    GUI/JusPrin/PrinterSetup/PrinterCatalog.hpp
    GUI/JusPrin/PrinterSetup/PrinterDiscovery.cpp
    GUI/JusPrin/PrinterSetup/PrinterDiscovery.hpp
    GUI/JusPrin/PrinterSetup/PrinterPhoto.cpp
    GUI/JusPrin/PrinterSetup/PrinterPhoto.hpp
    GUI/JusPrin/PrinterSetup/PrinterRecognition.cpp
    GUI/JusPrin/PrinterSetup/PrinterRecognition.hpp
    GUI/JusPrin/PrinterSetup/PrinterSetupController.cpp
    GUI/JusPrin/PrinterSetup/PrinterSetupController.hpp
    GUI/JusPrin/PrinterSetup/PrinterSetupDialog.cpp
    GUI/JusPrin/PrinterSetup/PrinterSetupDialog.hpp
    GUI/JusPrin/PrinterSetup/PrinterSetupLauncher.cpp
    GUI/JusPrin/PrinterSetup/PrinterSetupLauncher.hpp
    GUI/JusPrin/Home/HomeSnapshot.cpp
    GUI/JusPrin/Home/HomeSnapshot.hpp
    GUI/JusPrin/Home/HomeBackend.hpp
    GUI/JusPrin/Home/HomeHost.cpp
    GUI/JusPrin/Home/HomeHost.hpp
    GUI/JusPrin/Home/OrcaHomeBackend.cpp
    GUI/JusPrin/Home/OrcaHomeBackend.hpp
    GUI/JusPrin/Home/HomeWebView.cpp
    GUI/JusPrin/Home/HomeWebView.hpp
    GUI/JusPrin/Mcp/McpProtocol.cpp
    GUI/JusPrin/Mcp/McpProtocol.hpp
    GUI/JusPrin/Mcp/McpServer.cpp
    GUI/JusPrin/Mcp/McpServer.hpp
    GUI/JusPrin/Mcp/McpRuntime.cpp
    GUI/JusPrin/Mcp/McpRuntime.hpp
    GUI/JusPrin/Mcp/McpDiscoveryFile.cpp
    GUI/JusPrin/Mcp/McpDiscoveryFile.hpp
    GUI/JusPrin/Brand/BrandPalette.cpp
    GUI/JusPrin/Brand/BrandPalette.hpp
    GUI/JusPrin/CanvasPresentationController.cpp
    GUI/JusPrin/CanvasPresentationController.hpp
    GUI/JusPrin/Shell/AgentPane.cpp
    GUI/JusPrin/Shell/AgentPane.hpp
    GUI/JusPrin/Shell/McpSetupCommand.cpp
    GUI/JusPrin/Shell/McpSetupCommand.hpp
    GUI/JusPrin/Mcp/McpConnections.hpp
    GUI/JusPrin/Mcp/McpCatalog.cpp
    GUI/JusPrin/Mcp/McpCatalog.hpp
    GUI/JusPrin/Mcp/McpConfigFile.cpp
    GUI/JusPrin/Mcp/McpConfigFile.hpp
    GUI/JusPrin/Shell/ShellController.cpp
    GUI/JusPrin/Shell/ShellController.hpp
    GUI/JusPrin/Shell/ShellTheme.cpp
    GUI/JusPrin/Shell/ShellTheme.hpp
    GUI/JusPrin/Shell/ShellRecipes.cpp
    GUI/JusPrin/Shell/ShellRecipes.hpp
    GUI/JusPrin/Shell/StatusRow.cpp
    GUI/JusPrin/Shell/StatusRow.hpp
    GUI/JusPrin/Shell/HeaderControls.cpp
    GUI/JusPrin/Shell/HeaderControls.hpp
    GUI/JusPrin/Shell/PrinterSpoolChip.cpp
    GUI/JusPrin/Shell/PrinterSpoolChip.hpp
    GUI/JusPrin/Shell/PrinterMenu.cpp
    GUI/JusPrin/Shell/PrinterMenu.hpp
    GUI/JusPrin/Shell/SpoolMenu.cpp
    GUI/JusPrin/Shell/SpoolMenu.hpp
    GUI/JusPrin/Shell/SetupCommands.cpp
    GUI/JusPrin/Shell/SetupCommands.hpp
    GUI/JusPrin/Shell/PrimaryPrintAction.hpp
    GUI/JusPrin/Workspace/ModalAnswers.cpp
    GUI/JusPrin/Workspace/ModalAnswers.hpp
    GUI/JusPrin/Workspace/OrcaWorkspaceAdapter.cpp
    GUI/JusPrin/Workspace/OrcaGeometry.hpp
    GUI/JusPrin/Workspace/OrcaRegions.cpp
    GUI/JusPrin/Workspace/OrcaReshape.cpp
    GUI/JusPrin/Workspace/OrcaSliceChecks.cpp
    GUI/JusPrin/Workspace/OrcaOutputs.cpp
    GUI/JusPrin/Workspace/Regions.hpp
    GUI/JusPrin/Workspace/OrcaWorkspaceAdapter.hpp
    GUI/JusPrin/Workspace/PrinterFactsStore.cpp
    GUI/JusPrin/Workspace/PrinterFactsStore.hpp
    GUI/JusPrin/Workspace/PlaterProjectState.cpp
    GUI/JusPrin/Workspace/PlaterProjectState.hpp
    GUI/JusPrin/Workspace/ProjectState.hpp
    GUI/JusPrin/Workspace/Workspace.hpp
    GUI/JusPrin/Workspace/SpoolStore.cpp
    GUI/JusPrin/Workspace/SpoolStore.hpp
    GUI/JusPrin/Workspace/UtcTime.hpp
    GUI/JusPrin/Testing/FakeBambuAgent.cpp
    GUI/JusPrin/Testing/FakeBambuAgent.hpp
)

# Translation catalogs carrying the product name, built from upstream .po files.
include(${CMAKE_CURRENT_LIST_DIR}/Brand/catalogs.cmake)
